### ISSUE TITLE
Syntax error in implementation of __div() function

### ISSUE THREAD

**Issue by richardsonian** [brandonmcconnell/scss-typewriter#10]
I noticed an issue seemingly created by Pull Request #9 that was giving me the following sass compile error.

`typed.scss:41:in 'typed': Function __div is missing argument $number2. (Sass::SyntaxError)`

I believe this problem is occurring because the function implemented to divide two numbers, `__div(a, b)` is being called as `__div(a / b)` at multiple locations throughout the code.

I don't understand the LibSass / DartSass compatibility issue that makes the funciton `__div()` necessary in the first place, so I will not submit a pull request. I was however able to fix the compilation error and achieve a succesful typing animation when I went and replaced all instances of `__div(a / b)` with `__div(a, b)` (lines 41, 97, 145, 258).

**Comment by richardsonian** [comment]
Oh I wasn’t aware of [SASS Slash Separated Lists](https://github.com/sass/sass/blob/main/accepted/slash-separator.md).

For backwards compatibility though, wouldn’t it be best to implement __div() with comma separation? It certainly was the only solution that worked in my RubySass 3.4 dev environment.

**Comment by brandonmcconnell** [comment]
@richardsonian Thanks for the report! Hoping to resolve this one and the other you reported by next week. I just moved across the country, so I've been a bit preoccupied with that, but it should be soon. Thanks again! 🙂

**Comment by brandonmcconnell** [comment]
As I'm primarily stuck working in DartSass 1.32.0, do you know what the most correct and safe alternative for this would be?

I'll definitely replaces all, usage of `__div(num1 / num2)` with `__div(num1, num2)`, but do you if I'll also need to adjust the `__div` function itself at all?

### Current

```scss
$__supports-first-class-calc: calc(1) == 1;
@function __div($number1, $number2) {
  @if $__supports-first-class-calc {
    @return calc($number1 / $number2);
  } @else {
    @return $number1 / $number2;
  }
}
```

### Alternative (pseudo-code)

```scss
$__supports-math-div: math.div(1, 1) == 1; // I feel like this could throw an error in old SCSS versions 🤔
$__supports-first-class-calc: calc(1) == 1;
@function __div($number1, $number2) {
  @if $__supports-math-div {
    @return math.div($number1, $number2);
  @else if $__supports-first-class-calc {
    @return calc($number1 / $number2);
  } @else {
    @return $number1 / $number2;
  }
}
```

@nex3 I'm looping you in as well, as your help was instrumental in helping me resolve the related issue #6 (thanks again!).

Is there anything reverse compatible like a try…catch that I can use to safely check if `math.div` is supported in the current env?

**Comment by brandonmcconnell** [comment]
@richardsonian Could you please test and respond to my related PR #12, which should resolve this issue? Thanks!

**Comment by nex3** [comment]
> @nex3 I'm looping you in as well, as your help was instrumental in helping me resolve the related issue #6 (thanks again!).

It looks like your current function should work with `__div(num1, num2)`.

> Is there anything reverse compatible like a try…catch that I can use to safely check if `math.div` is supported in the current env?

The problem is, because LibSass doesn't support the module system at all, `math.div()` is _syntactically_ invalid in that case. You can in theory hack around syntactic incompatibilities using Dart Sass's support for import-only files, but I don't think you should need to do so here.

**Comment by brandonmcconnell** [comment]
@nex3 Thanks! I'll go ahead and merge #12 then. I really appreciate your feedback.
